apiVersion: apps/v1 
kind: Deployment 
metadata:
  labels:
    app: deploy-nginx
  name: deploy-nginx
  namespace: rq
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: deploy-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-nginx 
    spec:
      containers:
        - image: nginx 
          name: nginx 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi