apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: default
  labels:
    app: alpine
spec:
  containers:
  - name: latest
    image: alpine:latest
    command:
      - sleep
      - "5000"
  restartPolicy: Always