apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: nginx:stable-alpine
      ports:
       - containerPort: 80
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level